### ISSUE TITLE
Please upgrade pytorch_lightning

### ISSUE THREAD

**Issue by lucasjinreal** [roatienza/efficientspeech#3]
we are now in 2.0 as well as lightning_bolts, also, it was outdated since torch2.0, every single APi breaks

**Comment by v0xie** [comment]
Try my fork with latest Torch and Lightning, branch `feature/faster-training`: https://github.com/v0xie/efficientspeech/tree/feature/faster-training

**Comment by roatienza** [comment]
Upgraded to PyTorch2.0 and Lightning2.0
