### ISSUE TITLE
ONNX models?

### ISSUE THREAD

**Issue by fquirin** [roatienza/efficientspeech#4]
I've tried efficientspeech on my Raspberry Pi 4 and it works pretty well (~2s for 3s audio) 👍, but it still needs to be a bit faster to be really useful.
In your code I've seen a comment about the ONNX models being ~3 times faster.
I failed to use the convert script so I was wondering if you could upload the model for testing? 🙂

**Comment by roatienza** [comment]
[ONNX conversion](https://github.com/roatienza/efficientspeech/tree/main#onnx) now supported. 
There are certain limitations though like dynamic axis is not fully compatible with certain ops in feature upsampling.

**Comment by fquirin** [comment]
Ty for the update. I'm getting a few warnings during code execution, but it seems to work and it looks like the ONNX version is about twice as fast 😎 👍. Will do some more tests as soon as I find time.

Btw your RTF definition is flipped, faster than RT usually is <1 😉: [RTF](https://openvoice-tech.net/index.php/Real-time-factor)
